"""Run every sql/analysis/*.sql against gainesville.db.

Writes results/<name>.csv for each query and results/RESULTS.md (each query's question,
its output table, and a check against the reference numbers in docs/SPEC.md).
Usage: python src/run_queries.py
"""
import sqlite3
import sys
from datetime import datetime
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
DB_PATH = ROOT / "gainesville.db"
SQL_DIR = ROOT / "sql" / "analysis"
OUT_DIR = ROOT / "results"


def question(sql: str) -> str:
    for line in sql.splitlines():
        if line.startswith("-- Q:"):
            return line[len("-- Q:"):].strip()
    return ""


def md_table(df: pd.DataFrame) -> str:
    def cell(v):
        if pd.isna(v):
            return ""
        if isinstance(v, float):
            return f"{v:,.2f}".rstrip("0").rstrip(".") if v != int(v) else f"{int(v):,}"
        return str(v)
    head = "| " + " | ".join(df.columns) + " |"
    sep = "|" + "|".join("---" for _ in df.columns) + "|"
    rows = ["| " + " | ".join(cell(v) for v in r) + " |" for r in df.itertuples(index=False)]
    return "\n".join([head, sep, *rows])


def reference_checks(res: dict[str, pd.DataFrame]) -> pd.DataFrame:
    """Compare our outputs with the manual pull of Oct 8 2026 listed in docs/SPEC.md."""
    k = res["01_headline_kpis"].iloc[0]
    d = res["05_discount_leakage"].set_index("discount_type")["pct_of_gross_rent"]
    ch = res["06_channel_comparison"]
    lead = res["04_lead_time"]
    lost = res["13_lost_requests"]
    lost_per_req = lost[lost.platform == "vrbo"].groupby("lost_request")["already_sold_at_request"].max()
    rows = [
        ("Calendar nights Aug 15-Dec 31", 139, k.calendar_nights),
        ("Booked nights", 51, k.booked_nights),
        ("Occupancy %", 36.7, k.occupancy_pct),
        ("ADR $", 284.14, k.adr),
        ("Net revenue ex cleaning $", 8786.61, k.net_revenue),
        ("Reservation records", 15, int(ch.requests.sum())),
        ("Accepted", 9, int(ch.confirmed.sum())),
        ("Cancelled", 1, int(ch.cancelled.sum())),
        ("Vrbo declined or expired", 5, int(ch.loc[ch.platform == "vrbo", "lost"].sum())),
        ("Discounts % of gross rent", 22.5, d["TOTAL"]),
        ("  top-rated %", 8.4, d["top_rated"]),
        ("  weekly/monthly (length of stay) %", 9.7, d["length_of_stay"]),
        ("  promo %", 3.5, d["promo"]),
        ("  early booking %", 0.9, d["early_booking"]),
        ("Lost Vrbo requests overlapping already-sold dates", 5, int(lost_per_req.sum())),
        ("Median lead time (days)", 77, lead.loc[lead.bucket.str.contains("all stays"), "median_days"].iloc[0]),
    ]
    out = pd.DataFrame(rows, columns=["metric", "reference", "ours"])
    out["match"] = [("yes" if abs(float(o) - float(r)) < 0.01 else "NO") for r, o in zip(out.reference, out.ours)]
    return out


def main() -> None:
    if not DB_PATH.exists():
        sys.exit("gainesville.db not found. Run src/load.py first.")
    OUT_DIR.mkdir(exist_ok=True)
    con = sqlite3.connect(DB_PATH)
    results, sections = {}, []
    for path in sorted(SQL_DIR.glob("*.sql")):
        sql = path.read_text(encoding="utf-8")
        df = pd.read_sql(sql, con)
        results[path.stem] = df
        df.to_csv(OUT_DIR / f"{path.stem}.csv", index=False)
        sections.append(f"## {path.stem}\n\n**Question:** {question(sql)}\n\n"
                        f"Source: [`sql/analysis/{path.name}`](../sql/analysis/{path.name})\n\n{md_table(df)}\n")
        print(f"  {path.stem:<28} {len(df):>3} rows")
    con.close()

    ref = reference_checks(results)
    built = datetime.now().strftime("%Y-%m-%d %H:%M")
    md = (f"# Results\n\nGenerated by `src/run_queries.py` on {built} from `gainesville.db`. "
          "Each table below is the exact output of the query file named in its heading.\n\n"
          "## Check against the reference numbers (docs/SPEC.md, manual pull Oct 8 2026)\n\n"
          f"{md_table(ref)}\n\n" + "\n".join(sections))
    (OUT_DIR / "RESULTS.md").write_text(md, encoding="utf-8")

    print("\nReference check")
    print(ref.to_string(index=False))
    print(f"\nWrote {len(results)} CSVs and results/RESULTS.md")


if __name__ == "__main__":
    main()
